---
- name: Play to configure multi tier application
  hosts: all
  become: True
  gather_facts: false   # Speeds up the execution
  
  pre_tasks:
    -name: Copy and enable repo
      template:
        src: open_three-tier-app.repo
        dest: /etc/yum.repo.d/open_three-tier-app.repo
        mode: 0644
         
  roles:

    - role: HAproxy
      when: inventory_hostname in groups['frontends']
      
    - role: apache
      when: inventory_hostname in groups['apps']

    - role: tomcat
      when: inventory_hostname in groups['apps']

    - role: postgresql
      when: inventory_hostname in groups['appdbs']

